ubuntu20.sh
AndronixApp/AndronixOrigin pull request #31
Opened 2020-05-15 14:55 UTC by VISHAWANATH953

Making add on this many times am runs vncserver and exit on this it will runs also exited but runs vncserver so this added on this thats can exit all this background running processes so this matter for i am added on this

2020-05-15 15:04 UTC, VISHAWANATH953 commented
If this was ok for you make change all script thats run a linux binarys

2020-10-16 14:58 UTC, deril1 requested changes
VISHAWANATH953:patch-1

2020-10-16 15:33 UTC, deril1 requested changes
Installer/Ubuntu20/ubuntu20.sh

2020-11-07 20:35 UTC, jmodes approved these changes

2020-11-20 07:30 UTC, jonbrown1981 approved these changes

2020-11-20 08:16 UTC, jonbrown1981 approved these changes
`@`

2020-11-20 08:18 UTC, jonbrown1981 approved these changes

2020-12-05 12:06 UTC, daddivan69 approved these changes

2020-12-05 12:06 UTC, daddivan69 commented on Installer/Ubuntu20/ubuntu20.sh
> +command+=" --kill-on-exit"
```suggestion
command+=" --kill-on-exit"
```

2020-12-24 21:52 UTC, daddivan69 approved these changes

2021-01-23 19:50 UTC, jmodes approved these changes
Works

2021-01-23 19:52 UTC, jmodes commented
??

2021-01-25 11:09 UTC, VISHAWANATH953 commented on Installer/Ubuntu20/ubuntu20.sh
> +command+=" --kill-on-exit"
ok, this was seen like double things like it.

2021-01-28 15:53 UTC, ultrahacx commented
Thanks for your effort but we'll be adding the following changes with some additional binds so Im closing this pull request. We still appreciate the effort to make the community better♥.

2021-01-28 15:53 UTC, closed without merging